### ISSUE TITLE
Fatal error: Uncaught Error: Class 'SoapClient' not found

### ISSUE THREAD

**Issue by Langlais115** [Sage-ERP-X3/sample-x3-ws-php-webportal#1]
Hi There

When I try use your webservice I got the following error
```
Fatal error: Uncaught Error: Class 'SoapClient' not found in /var/www/sample-x3-ws-php-webportal
/WebService/modelWS/ModelX3.php on line 30
```

After a quick search I can't find the definition of the class '**SoapClient**'.

Does the project is missing a file?
If not can you please point it to me when does the definition of this class is located?

Thanks,

**Comment by oliviermantel** [comment]
You must enable the soap library

[see](https://stackoverflow.com/questions/11584426/how-do-i-enable-enable-soap-in-php-on-linux)
