### ISSUE TITLE
Error, file missing

### ISSUE THREAD

**Issue by Dydimox** [Sage-ERP-X3/sample-x3-ws-php-webportal#4]
Bonjour,

J'ai suivi la documentation de ce projet.
Cependant, il m'est impossible de faire une requête correcte. Voici ce que Sage X3 me dit lorsque je lance ma requête:

X3 Error: @X3.TRT/AWEB$adx, message:E:\Sage\X3V12MIG\dossiers\X3\TRT\AWEB.src : File Non-existent, line :736, type:1

<img width="672" alt="raaaa" src="https://user-images.githubusercontent.com/19407668/87022305-95e20080-c1d6-11ea-9059-bcaaf7848aa3.PNG">

Je n'ai aucun autre point bloquant. Impossible pour moi de faire fonctionner mon Web service.

Version Sage : V12

**Comment by oliviermantel** [comment]
Avez-vous toujours pb?

**Comment by Dydimox** [comment]
Non le problème à été réglé ! Je clos donc a la suite de ce message.
